/* Generated by gb2cpc asset_converter -- do not edit by hand. */
#ifndef PLAYER_H
#define PLAYER_H

#define PLAYER_NUM_TILES 1
#define PLAYER_TILE_BYTES 16

const unsigned char player_palette[4] = { 11, 6, 26, 12 };

const unsigned char player[16] = {
    0x11, 0x88, 0x33, 0xCC, 0x77, 0xEE, 0xFF, 0xFF, 0xFF, 0xFF, 0x77, 0xEE, 0x33, 0xCC, 0x11, 0x88,
};

#endif /* PLAYER_H */
