"""Emit C source/header from converted assets."""

from __future__ import annotations

from typing import List, Sequence

from .palette import PaletteMapping


def _byte_rows(flat: Sequence[int], per_line: int = 16) -> str:
    lines = []
    for i in range(0, len(flat), per_line):
        chunk = flat[i : i + per_line]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return "\n".join(lines)


def emit_header(
    tiles: List[List[int]],
    array_name: str,
    palette: PaletteMapping | None = None,
    guard: str | None = None,
) -> str:
    """Build a C header containing the CPC tile data (and optional palette).

    Each tile is 16 bytes; tiles are concatenated into a single flat array so
    the runtime can address tile ``n`` at ``array[n * 16]``.
    """
    guard = guard or (array_name.upper() + "_H")
    flat: List[int] = [b for tile in tiles for b in tile]

    parts: List[str] = []
    parts.append("/* Generated by gb2cpc asset_converter -- do not edit by hand. */")
    parts.append(f"#ifndef {guard}")
    parts.append(f"#define {guard}")
    parts.append("")
    parts.append(f"#define {array_name.upper()}_NUM_TILES {len(tiles)}")
    parts.append(f"#define {array_name.upper()}_TILE_BYTES 16")
    parts.append("")

    if palette is not None:
        parts.append(palette.as_c_array(array_name + "_palette"))

    parts.append(f"const unsigned char {array_name}[{len(flat)}] = {{")
    parts.append(_byte_rows(flat))
    parts.append("};")
    parts.append("")
    parts.append(f"#endif /* {guard} */")
    parts.append("")
    return "\n".join(parts)
